### ISSUE TITLE
Les boutons de gestion de demande ne s'affichent pas

### ISSUE THREAD

**Issue by annemarie35** [betagouv/signup.api.gouv.fr-back#40]
- je me connecte avec contact@particulier.api.gouv.fr
- je clique sur une demande
- je ne peux que ‘VOIR’ la demande.
- j’ai envoyé la demande en tant que use
- je vois la “demande envoyée” en tant que contact@particulier.api.gouv.fr

**Comment by pknoth** [comment]
devrais être corrigé par : https://github.com/betagouv/signup.api.gouv.fr-back/pull/37/commits/5dba9ce3f5e7a1c7f142db3f6ee156dd916a446f
